# Docker Compose for Bravix ERP Frontend Only
# Frontend: app.bravix.vn
# Backend: api.bravix.vn (external)

version: '3.8'

services:
  # ======================================
  # Frontend Service (React + Nginx)
  # ======================================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: bravix_frontend
    restart: unless-stopped
    environment:
      # Application configuration
      - VITE_APP_ENV=production
      - VITE_ACCESS_TOKEN_THRESHOLD=120000
      - VITE_DOMAIN=https://app.bravix.vn
      - VITE_API_URL=https://api.bravix.vn
      - VITE_USER_TYPE=staff
      # Optional external services
      - VITE_APP_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - VITE_APP_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - VITE_ROLLBAR_CLIENT_TOKEN=${ROLLBAR_TOKEN:-}
      - VITE_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY:-}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - frontend_network

# ======================================
# Networks
# ======================================
networks:
  frontend_network:
    driver: bridge

# ======================================
# Volumes
# ======================================
volumes:
  # Application logs
  nginx_logs:
    driver: local